### ISSUE TITLE
Missing profile managerment

### ISSUE THREAD

**Issue by Longnt1208** [jholovacs/pgprovider#10]
I tried to add more profile information of user like full name, address. mobile...but I can not and checked this in your code I didn't see this implementation. In fact, I can create a profile table and query information  from it but I see that you created this table so I think maybe have a missing here ?

**Comment by jholovacs** [comment]
There's no support for Profile info, this is authentication and authorization only.  If you need profile info, I'd suggest implementing ASP.NET Identity framework.  Membership framework support for profile data is awful.
